# Generated by Django 3.2.9 on 2022-01-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='path',
        ),
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(default='it should not exist', help_text='Track file', upload_to='audio'),
            preserve_default=False,
        ),
    ]
