# Generated by Django 3.2.9 on 2022-01-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220125_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(help_text='Track file', upload_to='static/audio'),
        ),
    ]
